#!/bin/bash
clear
echo "Trwa tworzenie struktury katalogow..."
T1=$(/usr/bin/whoami)
sudo mkdir -p /var/www/public_html/$T1/public_html
if [ $? -eq 0 ]; then
        echo -ne "Ok $(date '+%Y-%m-%d %H:%M:%S')\n"
        else
        echo -ne "Co¶ posz³o nie tak $(date '+%Y-%m-%d %H:%M:%S') \n"
        fi
echo "Nadawanie uprawnien..."
sudo chown -R $T1:$T1 /var/www/public_html/$T1/public_html
if [ $? -eq 0 ]; then
        echo -ne "Ok $(date '+%Y-%m-%d %H:%M:%S')\n"
        else
        echo -ne "Co¶ posz³o nie tak $(date '+%Y-%m-%d %H:%M:%S') \n"
        fi
echo "Tworzenie symbolicznego dowiazania..."
ln -s /var/www/public_html/$T1/public_html/ ~/public_html
if [ $? -eq 0 ]; then
        echo -ne "Ok $(date '+%Y-%m-%d %H:%M:%S')\n"
        else
        echo -ne "Co¶ posz³o nie tak $(date '+%Y-%m-%d %H:%M:%S') \n"
        fi

